### ISSUE TITLE
use unicode table

### ISSUE THREAD

**Issue by tmcw** [mapbox/font-scope#5]
@nickidlugash 

Okay this is moderately tee-ed up

https://github.com/mapbox/font-scope/commit/52773ec04126eb840e209d45287071d194d2b63f

```
$ git clone https://github.com/mapbox/font-scope.git
$ cd font-scope
$ npm install
$ make
$ node process.js
```

See the source of process.js: this is going to involve [charCodeAt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt) to get each code and then a little logic to avoid couting the `[` `]` and ` ` characters as part of every language. When you're done, you'll want to dump it to json like

```js
fs.writeFileSync('output.json', JSON.stringify(output));
```

And then we'll be ready for step 2

**Comment by nickidlugash** [comment]
Capturing next to-dos:

1. Add character codes for characters in the "auxiliary", "punctuation", and "index" fields.
2. Add a field in each language object for the language's name in English.

**Comment by nickidlugash** [comment]
@tmcw Above steps are done if you want to [check it out here](https://github.com/mapbox/font-scope/blob/master/process.js). If you have edits, would you mind going over them with me? Thanks :) Also, I'm not sure this will run as is without updating the [Makefile](https://github.com/mapbox/font-scope/blob/master/Makefile) to create a 'json' folder when unzipping json.zip.

@kkaefer by any chance can you make sense of [these escape characters in the unicode data for which punctuation characters exist for each language](https://gist.github.com/nickidlugash/6714219d8c0f5bb3d2d0#file-characters-json-L17)? (The gist is a copy of the json file for English.) For now I (hackily) removed them from the string of characters before converting the characters to code points, but @tmcw and I can't figure out why they are written like that in the first place.

**Comment by kkaefer** [comment]
@nickidlugash I'm at a bit of a loss as to what this is supposed to do. Can you please explain the context of this thing?

**Comment by mikemorris** [comment]
@nickidlugash By escape chars,  you mean the `\\` or `\` preceding some of the punctuation chars? My guess is that it's intended to prevent `JSON.parse` errors, although the encoding is quite strange - stringified space-delimited arrays?

**Comment by nickidlugash** [comment]
> Can you please explain the context of this thing?

The `process.js` takes [json files provided by Unicode](http://www.unicode.org/Public/cldr/26.0.1/) that list the unicode characters needed to display a given language, and converts them to lists of code points for each language. The next step will be to compare these lists of code points to the set of code points supported in a provided font, and output the % of each language this font supports.

>  By escape chars, you mean the \\ or \ preceding some of the punctuation chars?

Yep. 

> My guess is that it's intended to prevent JSON.parse errors, although the encoding is quite strange - stringified space-delimited arrays?

So currently when I parse these files without removing the `\\`, the output includes a `\` for each `\\`, but I don't know what the purpose of that is. On Unicode's own site, they display these characters with the `\` in front of them, but I'm not sure why.

**Comment by kkaefer** [comment]
@nickidlugash my hunch is that they use some sort of POSIX regular expression syntax rather than PCRE that most web languages use. This would explain the escaping of `[`, `]`, `:` and `-`, but it doesn't explain the `&`. 

Apart from that, you should make sure that you correctly convert surrogate pairs to codepoints; this is tricky in JS since it only supports UCS-2 rather than proper UTF-8.

**Comment by nickidlugash** [comment]
@kkaefer thanks for taking a look!

> you should make sure that you correctly convert surrogate pairs to codepoints; this is tricky in JS since it only supports UCS-2 rather than proper UTF-8.

Thanks, will look into this. Right now there's multiple inaccuracies with the list of code points I'm generating, but I'll keep working on getting this tighter.

**Comment by tmcw** [comment]
Cool: round two!

I've created a v2 branch and pushed the output of the glyphs api for Lato, a font with not-much-coverage and Arial Unicode, the font-that-has-everything. Basically: big arrays of numbers.

Mission is to write a node script that requires the json for these fonts, the json for strings, and compares the two, giving a % of each language covered.

The algorithm is something like

```
intersection(codePointsInLanguage, codePointsInFont).length / codePointsInLanguage = % covered
```

Something like [_.intersection](https://lodash.com/docs#intersection) may help you in this quest.

**Comment by nickidlugash** [comment]
@tmcw I basically have this working in the [`compare.js` script](https://github.com/mapbox/font-scope/blob/master/compare.js). It just console logs the output right now. the % coverage of each font looks about right, but I haven't confirmed for sure yet. Maybe we can take a look at this together next week?

**Comment by nickidlugash** [comment]
@tmcw per voice, could you link here where/how I can output the json file of code points for any font we have in our api?

**Comment by tmcw** [comment]
* listing of fonts: http://api.tiles.mapbox.com/v4/fontstack.json?access_token=pk.eyJ1IjoidG1jdyIsImEiOiJIZmRUQjRBIn0.lRARalfaGHnPdRcc-7QZYQ
* codepoints of a font http://api.tiles.mapbox.com/v4/fontstack/Call%20Three%20OT%20Italic.json?access_token=pk.eyJ1IjoidG1jdyIsImEiOiJIZmRUQjRBIn0.lRARalfaGHnPdRcc-7QZYQ

follow the same pattern - copy a font name where Call Three Italic is in the second url

**Comment by tmcw** [comment]
Donezo
